import type { PromotionRow, PromotionsProps } from './Promotions.types'

export const promotionsPageRows: PromotionRow[] = [
  {
    id: 'promo-may-audio-flash',
    name: 'May Audio Flash',
    status: 'LIVE',
    kind: 'FLASH',
    startsAtLabel: 'May 10, 2026',
    endsAtLabel: 'May 13, 2026',
    offerLabel: '25% off',
    productCount: 3,
    progressCurrent: 312,
    progressTarget: 500,
    active: true,
  },
  {
    id: 'promo-bundle-desk-setup',
    name: 'Bundle: Desk Setup',
    status: 'LIVE',
    kind: 'BUNDLE',
    startsAtLabel: 'May 8, 2026',
    endsAtLabel: 'May 25, 2026',
    offerLabel: '15% off',
    productCount: 3,
    progressCurrent: 96,
    progressTarget: 1000,
    active: true,
  },
  {
    id: 'promo-weekend-discount',
    name: 'Weekend Discount',
    status: 'SCHEDULED',
    kind: 'DISCOUNT',
    startsAtLabel: 'May 14, 2026',
    endsAtLabel: 'May 16, 2026',
    offerLabel: '10% off',
    productCount: 2,
    progressCurrent: 0,
    progressTarget: 2000,
    active: false,
  },
  {
    id: 'promo-new-launch-teaser',
    name: 'New launch teaser',
    status: 'DRAFT',
    kind: 'DISCOUNT',
    startsAtLabel: 'May 21, 2026',
    endsAtLabel: 'May 28, 2026',
    offerLabel: '20% off',
    productCount: 0,
    progressCurrent: 0,
    progressTarget: 500,
    active: false,
  },
  {
    id: 'promo-spring-clearance',
    name: 'Spring Clearance',
    status: 'ENDED',
    kind: 'DISCOUNT',
    startsAtLabel: 'Apr 11, 2026',
    endsAtLabel: 'May 4, 2026',
    offerLabel: '30% off',
    productCount: 2,
    progressCurrent: 1820,
    progressTarget: 2000,
    active: false,
  },
]

export const promotionsDefaultProps = {
  title: 'Promotions',
  description: 'Run flash deals, bundles and discounts to drive conversion',
  newPromotionHref: '#',
  promotions: promotionsPageRows,
  onEdit: () => {},
  onDuplicate: () => {},
  onActiveChange: () => {},
} satisfies Required<PromotionsProps>
