/**
 * OpenAPI → TypeScript type generation script.
 *
 * Reads the committed OpenAPI JSON specs from each NestJS API app and
 * generates strongly-typed TypeScript definitions using openapi-typescript.
 *
 * Output files are committed to packages/contracts/src/generated/ and
 * MUST NOT be manually edited — they are regenerated on every swagger:gen run.
 *
 * Usage:
 *   node packages/contracts/scripts/generate-types.mjs
 *   (or via: pnpm openapi:gen from the repo root)
 *
 * Migration path (Phase 3+):
 *   - Frontend API call files will be migrated to use these generated types
 *     instead of hand-written interfaces.
 *   - Use `paths["~1admin~1auth~1login"]["post"]["responses"]["200"]["content"]["application/json"]`
 *     pattern to extract per-endpoint response types.
 *   - Wrap with the ApiSuccessResponse<T> envelope from @ecom/contracts/http.
 */

import openapiTS, { astToString } from 'openapi-typescript'
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const repoRoot = resolve(__dirname, '../../..')
const outputDir = resolve(__dirname, '../src/generated')

if (!existsSync(outputDir)) {
  mkdirSync(outputDir, { recursive: true })
}

const specs = [
  {
    name: 'admin',
    input: resolve(repoRoot, 'apps/api-admin/openapi/admin.json'),
    output: resolve(outputDir, 'admin.ts'),
  },
  {
    name: 'seller',
    input: resolve(repoRoot, 'apps/api-seller/openapi/seller.json'),
    output: resolve(outputDir, 'seller.ts'),
  },
  {
    name: 'storefront',
    input: resolve(repoRoot, 'apps/api-storefront/openapi/storefront.json'),
    output: resolve(outputDir, 'storefront.ts'),
  },
]

const banner = `/**
 * AUTO-GENERATED FILE — DO NOT EDIT MANUALLY.
 *
 * Generated by openapi-typescript from the OpenAPI spec.
 * Regenerate with: pnpm openapi:gen
 *
 * Source of truth: apps/api-<name>/openapi/<name>.json
 * (which is itself generated from NestJS source via: pnpm swagger:gen:all)
 */

`

let hasError = false

for (const spec of specs) {
  if (!existsSync(spec.input)) {
    console.warn(
      `[openapi-gen] SKIP ${spec.name}: spec file not found at ${spec.input}.\n` +
        `  Run "pnpm swagger:gen:all" first to generate the OpenAPI specs.`,
    )
    continue
  }

  try {
    const schemaText = readFileSync(spec.input, 'utf-8')
    const schema = JSON.parse(schemaText)

    const ast = await openapiTS(schema, {
      exportType: true,
    })
    const output = banner + astToString(ast)

    writeFileSync(spec.output, output, 'utf-8')
    console.log(`[openapi-gen] ✓ Generated ${spec.output}`)
  } catch (err) {
    console.error(`[openapi-gen] ✗ Failed to generate types for ${spec.name}:`, err)
    hasError = true
  }
}

if (hasError) {
  process.exit(1)
}
