import type { InventoryRow, InventoryProps } from './Inventory.types'
import { inventoryColumns, filterInventory } from './Inventory.utils'

export const inventoryPageRows: InventoryRow[] = [
  {
    id: 'LUM-1000',
    image:
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=96&q=80',
    name: 'Wireless ANC Headphones — Studio Edition',
    category: 'Electronics',
    sku: 'LUM-1000',
    onHand: 5,
    incoming: 0,
    reserved: 3,
    available: 2,
    threshold: 10,
    status: 'Low',
  },
  {
    id: 'LUM-1001',
    image:
      'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=96&q=80',
    name: 'Linen Lounge Set, Oversized Fit',
    category: 'Fashion',
    sku: 'LUM-1001',
    onHand: 12,
    incoming: 0,
    reserved: 3,
    available: 9,
    threshold: 10,
    status: 'OK',
  },
  {
    id: 'LUM-1002',
    image:
      'https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?auto=format&fit=crop&w=96&q=80',
    name: 'Mechanical Keyboard, Hot-Swap 75%',
    category: 'Home & Living',
    sku: 'LUM-1002',
    onHand: 19,
    incoming: 0,
    reserved: 3,
    available: 16,
    threshold: 10,
    status: 'OK',
  },
  {
    id: 'LUM-1003',
    image:
      'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=96&q=80',
    name: 'Ceramic Pour-Over Coffee Set',
    category: 'Beauty',
    sku: 'LUM-1003',
    onHand: 26,
    incoming: 0,
    reserved: 3,
    available: 23,
    threshold: 10,
    status: 'OK',
  },
  {
    id: 'LUM-1004',
    image:
      'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=96&q=80',
    name: 'Minimalist Leather Card Holder',
    category: 'Grocery',
    sku: 'LUM-1004',
    onHand: 33,
    incoming: 0,
    reserved: 3,
    available: 30,
    threshold: 10,
    status: 'OK',
  },
  {
    id: 'LUM-1005',
    image:
      'https://images.unsplash.com/photo-1517705008128-361805f42e86?auto=format&fit=crop&w=96&q=80',
    name: 'Smart Desk Lamp with USB-C',
    category: 'Sports',
    sku: 'LUM-1005',
    onHand: 40,
    incoming: 0,
    reserved: 3,
    available: 37,
    threshold: 10,
    status: 'OK',
  },
  {
    id: 'LUM-1006',
    image:
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=96&q=80',
    name: 'Performance Running Shoes v3',
    category: 'Toys & Kids',
    sku: 'LUM-1006',
    onHand: 47,
    incoming: 0,
    reserved: 3,
    available: 44,
    threshold: 10,
    status: 'OK',
  },
  {
    id: 'LUM-1007',
    image:
      'https://images.unsplash.com/photo-1616627547584-bf28cee262db?auto=format&fit=crop&w=96&q=80',
    name: 'Aroma Diffuser, Walnut Wood',
    category: 'Mobile',
    sku: 'LUM-1007',
    onHand: 54,
    incoming: 0,
    reserved: 3,
    available: 51,
    threshold: 10,
    status: 'OK',
  },
  {
    id: 'LUM-1008',
    image:
      'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=96&q=80',
    name: 'Travel Backpack 24L Water-Resistant',
    category: 'Audio',
    sku: 'LUM-1008',
    onHand: 61,
    incoming: 0,
    reserved: 3,
    available: 58,
    threshold: 10,
    status: 'OK',
  },
]

export const inventoryDefaultProps = {
  title: 'Inventory',
  description: 'Manage stock levels across all SKUs',
  exportHref: '#export',
  inventory: inventoryPageRows,
  columns: inventoryColumns,
  searchPlaceholder: 'Search SKU or product...',
  emptyMessage: 'No inventory items match the current filters',
  filterInventory,
} satisfies Required<InventoryProps>
