packages:
  - apps/*
  - packages/*
allowBuilds:
  esbuild: false
  msw: false

ignoredBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/engines'
  - argon2
  - bcrypt
  - esbuild
  - msgpackr-extract
  - prisma
  - sharp
  - unrs-resolver
