export enum InventoryTransactionType {
  INBOUND = 'INBOUND',
  OUTBOUND = 'OUTBOUND',
  ADJUSTMENT = 'ADJUSTMENT',
  TRANSFER = 'TRANSFER',
  RETURN = 'RETURN',
  RESERVATION = 'RESERVATION',
  RESERVATION_RELEASE = 'RESERVATION_RELEASE',
  STOCK_OUT = 'STOCK_OUT',
}

export const INVENTORY_DEFAULTS = {
  MIN_STOCK_THRESHOLD: 5,
} as const;
