export enum UserStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
  BANNED = 'BANNED',
}

export enum UserRole {
  ADMIN = 'ADMIN',
  SELLER = 'SELLER',
  CUSTOMER = 'CUSTOMER',
  MODERATOR = 'MODERATOR',
}

export enum UserEventType {
  CREATED = 'CREATED',
  UPDATED = 'UPDATED',
  DELETED = 'DELETED',
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  PRODUCT_VIEW = 'PRODUCT_VIEW',
  PRODUCT_CLICK = 'PRODUCT_CLICK',
}
